### ISSUE TITLE
Issues/To-Dos

### ISSUE THREAD

**Issue by vishnuteja97** [JamesChapmanNV/NFL_database#1]
3/21/2024

1.) Venues table - Drop zipcode, combine city and state into a single field
2.) Rosters table - Remove active. change didnotplay -> played and flip the values
3.) Teams table - Remove teamid. Use teamname as primary key (simplifying assumption that team name is unique identifier)
4.) Games table - Remove name and shortname.
5.) Athletes table - Remove drafted_bool
6.) Positions table, Venue table - Remove numeric id with names as keys
7.) Teams table - Remove AFC, NFC (Irvin, Rice maybe as well)
8.) Plays table - Add start_down, end_down

**Comment by JamesChapmanNV** [comment]
**1.) Venues table - Drop zipcode, combine city and state into a single field
----- ISSUE -----**

Complete 2̶.̶)̶ ̶R̶o̶s̶t̶e̶r̶s̶ ̶t̶a̶b̶l̶e̶ ̶-̶ ̶R̶e̶m̶o̶v̶e̶ ̶a̶c̶t̶i̶v̶e̶.̶ ̶c̶h̶a̶n̶g̶e̶ ̶d̶i̶d̶n̶o̶t̶p̶l̶a̶y̶ ̶-̶>̶ ̶p̶l̶a̶y̶e̶d̶ ̶a̶n̶d̶ ̶f̶l̶i̶p̶ ̶t̶h̶e̶ ̶v̶a̶l̶u̶e̶s̶ ̶
Complete 3̶.̶)̶ ̶T̶e̶a̶m̶s̶ ̶t̶a̶b̶l̶e̶ ̶-̶ ̶R̶e̶m̶o̶v̶e̶ ̶t̶e̶a̶m̶i̶d̶.̶ ̶U̶s̶e̶ ̶t̶e̶a̶m̶n̶a̶m̶e̶ ̶a̶s̶ ̶p̶r̶i̶m̶a̶r̶y̶ ̶k̶e̶y̶ ̶(̶s̶i̶m̶p̶l̶i̶f̶y̶i̶n̶g̶ ̶a̶s̶s̶u̶m̶p̶t̶i̶o̶n̶ ̶t̶h̶a̶t̶ ̶t̶e̶a̶m̶ ̶n̶a̶m̶e̶ ̶i̶s̶ ̶Complete u̶n̶i̶q̶u̶e̶ ̶i̶d̶e̶n̶t̶i̶f̶i̶e̶r̶)̶ ̶
Complete 4̶.̶)̶ ̶G̶a̶m̶e̶s̶ ̶t̶a̶b̶l̶e̶ ̶-̶ ̶R̶e̶m̶o̶v̶e̶ ̶n̶a̶m̶e̶ ̶a̶n̶d̶ ̶s̶h̶o̶r̶t̶n̶a̶m̶e̶.̶ ̶
Complete 5̶.̶)̶ ̶A̶t̶h̶l̶e̶t̶e̶s̶ ̶t̶a̶b̶l̶e̶ ̶-̶ ̶R̶e̶m̶o̶v̶e̶ ̶d̶r̶a̶f̶t̶e̶d̶_̶b̶o̶o̶l̶ ̶
Complete 6̶.̶)̶ ̶P̶o̶s̶i̶t̶i̶o̶n̶s̶ ̶t̶a̶b̶l̶e̶,̶ ̶V̶e̶n̶u̶e̶ ̶t̶a̶b̶l̶e̶ ̶-̶ ̶R̶e̶m̶o̶v̶e̶ ̶n̶u̶m̶e̶r̶i̶c̶ ̶i̶d̶ ̶w̶i̶t̶h̶ ̶n̶a̶m̶e̶s̶ ̶a̶s̶ ̶k̶e̶y̶s̶ ̶
Complete 7̶.̶)̶ ̶T̶e̶a̶m̶s̶ ̶t̶a̶b̶l̶e̶ ̶-̶ ̶R̶e̶m̶o̶v̶e̶ ̶A̶F̶C̶,̶ ̶N̶F̶C̶ ̶(̶I̶r̶v̶i̶n̶,̶ ̶R̶i̶c̶e̶ ̶m̶a̶y̶b̶e̶ ̶a̶s̶ ̶w̶e̶l̶l̶)̶ ̶

**8.) Plays table - Add start_down, end_down**

**Comment by JamesChapmanNV** [comment]
Should we close this?
