### ISSUE TITLE
Duplicate data in athletes table

### ISSUE THREAD

**Issue by cazumbaugh3** [JamesChapmanNV/NFL_database#2]
The athletes table contains duplicate entries for several athletes. Needs fix in the following tables:
* Athletes
* Rosters
* Player_Plays

**Comment by JamesChapmanNV** [comment]
We could run this bit of code. 

It finds all rows in the athletes table with the same firstName, lastName, and dob (this is all the athletes with multiple athlete IDs). 

Then it changes the rosters table, by setting all of the ID PAIRS to the 2nd ID. For example, Change all athlete_id= 13279 to 2219984.

athletesDUPLICATES = athletes[athletes.duplicated(keep=False, subset=['firstName','lastName','dob'])][['firstName','lastName','dob']].copy()
athletesDUPLICATES.drop_duplicates(inplace=True)
athletesDUPLICATES = athletesDUPLICATES.dropna()
for row in athletesDUPLICATES.to_numpy():
    IdS = (athletes.loc[(athletes['firstName']==row[0])& (athletes['lastName']==row[1])& (athletes['dob']==row[2])]['athlete_id']).dropna().unique()
    print(row[0],row[1],row[2])
    print('--Change all athlete_id=',IdS[0],'to',IdS[1])
    rosters.loc[(rosters['athlete_id']==IdS[0]),'athlete_id']= IdS[1]

------------------------
OUTPUT
------------------------
Mike Johnson 04-02-1987
--Change all athlete_id= 13279 to 2219984
Branden Albert 11-04-1984
--Change all athlete_id= 11249 to 3938599
Tom Johnson 08-30-1984
--Change all athlete_id= 10001 to 16695
Willie Smith 11-13-1986
--Change all athlete_id= 14447 to 2219931
Brandon Scherff 12-26-1991
--Change all athlete_id= 2511708 to 4287933
Chris Manhertz 04-10-1992
--Change all athlete_id= 2531358 to 4071345
De'Angelo Henderson 11-24-1992
--Change all athlete_id= 2968226 to 2565755
------------------------
