### ISSUE TITLE
Venues need capacity

### ISSUE THREAD

**Issue by cazumbaugh3** [JamesChapmanNV/NFL_database#3]
Need to add capacity for each venue in the venues table. Currently listed as 0 for all.

**Comment by JamesChapmanNV** [comment]
Complete

**Comment by cazumbaugh3** [comment]
@JamesChapmanNV I don't see this reflected in the csv file. Was this just updated in the notebook?

**Comment by cazumbaugh3** [comment]
Added venue capacity in commit 36332f4.
